# Analyse de données de numpy

## Objectif

In [3]:
import numpy as np

world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75", skip_header = 1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## effectuer des comparaisons 

In [19]:
vector = np.array([5,10,15,20,10])

In [20]:
vector == 10

array([False,  True, False, False,  True])

In [21]:
matrix = np.array([[5,10,15], [20,25,30],[35,40,45]])
matrix 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

## Selectionner des éléments precis depuis un tableau numpy

In [23]:
vector

array([ 5, 10, 15, 20, 10])

In [24]:
equal_to_10 = (vector == 10)
print(vector[equal_to_10])

[10 10]


In [25]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
equal_to_25 = (matrix[:,1] == 25)

In [33]:
print(matrix[equal_to_25, :])

[[20 25 30]]


###  Effectuer des comparaison avec plusieurs conditions 

In [34]:
vector

array([ 5, 10, 15, 20, 10])

In [35]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)

In [36]:
print(equal_to_ten_and_five)

[False False False False False]


In [37]:
equal_to_ten_and_five = (vector == 10) | (vector == 5)
print(equal_to_ten_and_five)

[ True  True False False  True]
